const GENERATED_NOTICE = "<!-- Generated by .agent/tools/agent-rules. Edit source files under .agent/rules/, .agent/skills/, .agent/team/, .agent/adapters/, .agent/templates/. -->\n\n";
const LOCAL_NOTICE = "<!-- Generated by .agent/tools/agent-rules init. This local file is ignored by git; rerun init to refresh identity. -->\n\n";
const COMMANDS = new Set(["init", "sync", "doctor"]);
const DEFAULT_LANGUAGE = "简体中文";
const DEFAULT_ROLE = "全栈开发";

module.exports = {
  COMMANDS,
  DEFAULT_LANGUAGE,
  DEFAULT_ROLE,
  GENERATED_NOTICE,
  LOCAL_NOTICE,
};
